### ISSUE TITLE
Going into Settings, crashes App

### ISSUE THREAD

**Issue by Delorean12DMC** [aloussase/AlexandriaApp#23] opened 2024-03-27 06:34 UTC
When i enter the newly added configuration menu, the app crashes instantly.

Im using it on an OnePlus CPH2493 using Android 14 aarch64.

**Comment by linuzzx** [comment] 2024-03-27 11:43
Same, when it finally works, I'll donate a few bucks @aloussase ✨

**Comment by aloussase** [comment] 2024-03-27 12:50
I just did a fresh install from FDroid and it's working fine for me. Can't reproduce the issue. Try doing a fresh install.

**Comment by Delorean12DMC** [comment] 2024-03-27 17:43
Well i don't know exactly how it works, but shouldn't it be the case, that you have a collection of different language strings and if the language matches with the device language it's applied and if it's not found it just falls back to the stock setting which in your case is spanish?

**Comment by aloussase** [comment] 2024-03-27 17:47
Yes that's exactly the case. But, for example, what value should I use for english? en? en-us? Who knows. In the devices I tested it was en for english, de for german, but I can't be sure that it's like that in all devices.

**Comment by NotMeyi** [comment] 2024-03-30 01:44
Hello, I am having the same issue on the latest version. My app also crashes when i try to search for a book with the search bar.

**Comment by Delorean12DMC** [comment] 2024-03-30 18:06
The only solution i could think of is, that if the language code from the device is for example en-us, but your app just has en for english, it should generate an exception, in that case just implement a string comparison in the exception state, that checks if the language string contains for example en and just return that language instead, because english should have en-US and en-UK so the beginning in both strings is the same and so it is an easy comparison and decision to make and that could take care of it. I have to take a look at the code, i don't know if i'm able to successfully check it, because i'm more into C# and i don't have a development environment set up. Maybe i can help you with it, but don't take my word for granted in that case.

**Comment by aloussase** [comment] 2024-03-31 17:28
I don't know. It still feels like a hack to me. And I read somewhere that it's better to just rely on the system's locale settings than manually setting the application's language. We just need more people to contribute with wanted translations.

I don't really see the point of having language settings in the app.

**Comment by aloussase** [comment] 2024-06-18 22:47
Hi guys, I finally got some time to work on the app again. I have added a fix to avoid crashing the app when accessing the settings screen with an unregistered locale. Expect the fix to be available from the next update on F-Droid. 

Im gonna close this issue for now, but feel free to re-open it if the problems persist. Cheers!

**Closed by aloussase** 2024-06-18 22:47 UTC
